-- PROGRESSION - 1


-- 1. **Create table city**
CREATE TABLE CITY
(
ID NUMBER(11),
name VARCHAR(50),
CONSTRAINT CITY_PK PRIMARY KEY(ID)
);
-- 2. **Create table referee**
CREATE TABLE REFREE
(
ID NUMBER(11),
NAME VARCHAR(50),
CONSTRAINT REFREE_PK PRIMARY KEY(ID)
);
-- 3. **Create table innings**
CREATE TABLE INNINGS
(
ID NUMBER(11),
innings_number NUMBER(11),
CONSTRAINT INNINGS_PK PRIMARY KEY(ID)
);

-- 4. **Create table extra_type**
CREATE TABLE EXTRA_TYPE
(
ID NUMBER(11),
NAME VARCHAR(50),
COACH VARCHAR(50),
HOME_CITY NUMBER(11),
CAPTAIN NUMBER(11),
CONSTRAINT EXTRA_TYPE_PK PRIMARY KEY(ID)
);
-- 5. **Create table skill**
CREATE TABLE SKILL
(
ID NUMBER(11),
NAME VARCHAR(50),
CONSTRAINT SKILL_PK PRIMARY KEY(ID)
);
-- 6. **Create table team**
CREATE TABLE TEAM
(
ID NUMBER(11),
NAME VARCHAR(50),
COACH VARCHAR(50),
HOME_CITY NUMBER(11),
CAPTAIN NUMBER(11),
CONSTRAINT TEAM_PK PRIMARY KEY(ID)
);
-- 7. **Create table player**
CREATE TABLE PLAYER
(
ID NUMBER(11),
NAME VARCHAR(50),
COUNTRY VARCHAR(50),
SKILL_ID NUMBER(11),
TEAM_ID NUMBER(11),
CONSTRAINT PLAYER_PK PRIMARY KEY(ID)
);
-- 8. **Create table venue**
CREATE TABLE VENUE
(
ID NUMBER(11),
STADIUM_NAME VARCHAR(50),
CITY_ID NUMBER(11),
CONSTRAINT VENUE_PK PRIMARY KEY(ID)
);
-- 9. **Create table event**
CREATE TABLE EVENT
(
ID NUMBER(11),
INNINGS_ID NUMBER(11),
EVENT_NO NUMBER(11),
RAIDER_ID NUMBER(11),
RAID_POINTS NUMBER(11),
DEFENDING_POINTS NUMBER(11),
CLOCK_IN_SECONDS NUMBER(11),
TEAM_ONE_SCORE NUMBER(11),
TEAM_TWO_SCORE NUMBER(11),
CONSTRAINT EVENT_PK PRIMARY KEY(ID)
);
-- 10. **Create table extra_event**
CREATE TABLE EXTRA_EVENT
(
ID NUMBER(11),
EVENT_ID NUMBER(11),
EXTRA_TYPE_ID NUMBER(11),
POINTS NUMBER(11),
SCORING_TEAM_ID NUMBER(11),
CONSTRAINT EXTRA_EVENT_PK PRIMARY KEY(ID)
);
-- 11. **Create table outcome**
CREATE TABLE OUTCOME
(
ID NUMBER(11),
STATUS VARCHAR(50),
WINNER_TEAM_ID NUMBER(11),
SCORE NUMBER(11),
PLAYER_OF_MATCH NUMBER(11),
CONSTRAINT OUTCOME_PK PRIMARY KEY(ID)
);
-- 12. **Create table game**
CREATE TABLE GAME
(
ID NUMBER(11),
GAME_DATE DATE,
TEAM_ID_1 NUMBER(11),
TEAM_ID_2 NUMBER(11),
VENUE_ID NUMBER(11),
OUTCOME_ID NUMBER(11),
REFREE_ID_1 NUMBER(11),
REFREE_ID_2 NUMBER(11),
FIRST_INNINGS_ID NUMBER(11),
SECOND_INNINGS_ID NUMBER(11),
CONSTRAINT GAME_PK PRIMARY KEY(ID)
);
-- 13. **Drop table city**
CREATE TABLE CITY2
AS(SELECT * FROM CITY
);
DROP TABLE CITY;
-- 14. **Drop table innings**
CREATE TABLE INNINGS2
AS(SELECT * FROM INNINGS
);
DROP TABLE INNINGS;
-- 15. **Drop table skill**
CREATE TABLE SKILL2
AS(SELECT * FROM SKILL
);
DROP TABLE SKILL;
-- 16. **Drop table extra_type**
CREATE TABLE EXTRA_TYPE2
AS(SELECT * FROM EXTRA_TYPE
);
DROP TABLE EXTRA_TYPE;